version: '3.8'

services:
  php-apache:
    image: php:8.2-apache
    container_name: vite_php
    volumes:
      - ./public:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: vite_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Vite_et_gourmand
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: